FROM windows-java-dotnet-build

SHELL ["powershell"]  
ARG BASE_URL  
ARG SECRET

RUN (New-Object System.Net.WebClient).DownloadFile('{0}/jnlpJars/agent.jar' -f $env:BASE_URL, 'agent.jar') ;  
ENTRYPOINT ["C:\\Java\\jre1.8.0_91\\bin\\java.exe", "-jar", ".\\agent.jar"]